# Generated by Django 3.2.4 on 2021-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210629_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='final_test',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mid_term_test',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
