version: '3.7'

services:
    backend:
        build: .
        command: python /backend/manage.py runserver 0.0.0.0:8000
        restart: always
        tty: true
        volumes:
            - .:/backend
        ports:
            - '8000:8000'
        depends_on:
            - db
    db:
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password --mysqlx=0
        environment:
            - MYSQL_HOST=localhost
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=qldt_db
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=123456

        ports:
            - '3306:3306'

        volumes:
            - '.db:/var/lib/mysql'
